-- ============================================================================
-- GPUnlock · 02 · Tablas de las landings (Vértice, Prisma, Valle Sereno) y portafolio
-- Mismo modelo de datos que ya usaban los sitios (Nivel 1: sin cambios de
-- estructura), ahora todo en un solo proyecto de Supabase.
-- Las políticas de acceso están en 06_politicas.sql.
-- ============================================================================

-- Vértice -------------------------------------------------------------------
create table if not exists public.units (
  code text primary key,
  kind text not null default 'suite',          -- 'suite' | 'local'
  grupo text,
  title text not null,
  tag text,
  area text,
  status text not null default 'disponible'
    check (status in ('disponible','reservado','vendido')),
  dorm text,
  banos text,
  extra text,
  ficha text,
  thumb text,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

-- Prisma --------------------------------------------------------------------
create table if not exists public.prisma_units (
  code text primary key,
  kind text not null default 'suite' check (kind in ('suite','loft','local','isla')),
  grupo text,
  title text not null,
  tag text,
  area text,
  status text not null default 'disponible'
    check (status in ('disponible','reservado','vendido')),
  dorm text,
  banos text,
  extra text,
  ficha text,
  thumb text,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

-- Valle Sereno -----------------------------------------------------------
create table if not exists public.lots (
  code text primary key,
  status text not null default 'disponible'
    check (status in ('disponible','reservado','no_disponible')),
  area numeric,
  price numeric,
  cx numeric not null default 50,
  cy numeric not null default 50,
  points jsonb,                                 -- polígono [[x,y],...] trazado sobre el plano
  updated_at timestamptz not null default now()
);

create table if not exists public.slider_images (
  id bigint generated by default as identity primary key,
  src text not null,
  alt text default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

-- Portafolio (landing principal GPUnlock) ---------------------------------------
create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  url text not null,
  tagline text,
  cover_url text,
  ubicacion text,
  tipo text,                                    -- ej. 'Suites y locales', 'Lotes'
  visible boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);
-- Columnas nuevas si la tabla ya existía:
alter table public.projects add column if not exists ubicacion text;
alter table public.projects add column if not exists tipo text;
alter table public.projects add column if not exists visible boolean not null default true;

-- updated_at automático ------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;

drop trigger if exists units_updated_at on public.units;
create trigger units_updated_at before update on public.units
  for each row execute function public.set_updated_at();
drop trigger if exists prisma_units_updated_at on public.prisma_units;
create trigger prisma_units_updated_at before update on public.prisma_units
  for each row execute function public.set_updated_at();
drop trigger if exists lots_updated_at on public.lots;
create trigger lots_updated_at before update on public.lots
  for each row execute function public.set_updated_at();

alter table public.units         enable row level security;
alter table public.prisma_units   enable row level security;
alter table public.lots          enable row level security;
alter table public.slider_images enable row level security;
alter table public.projects      enable row level security;

-- Storage público para imágenes de los sitios.
-- Carpetas: vertice/  prisma/  valle/  portafolio/  (una por proyecto)
insert into storage.buckets (id, name, public)
values ('site-images', 'site-images', true)
on conflict (id) do nothing;

-- Portafolio inicial (solo si la tabla está vacía). Los proyectos de demostración
-- vienen en 08_datos_demo.sql; aquí no se inserta nada.
